// This file demonstrates the type-safe Prisma client types
// These are automatically generated by Prisma

import { PrismaClient, Lead, Afspraak, RouteCluster, Customer, TimeSlot, BlockedDate } from '@prisma/client';

// Re-export the generated types for easy import
export type {
  Lead,
  Afspraak,
  RouteCluster,
  Customer,
  TimeSlot,
  BlockedDate,
  AfspraakStatus,
  ServiceType,
  KlantType
} from '@prisma/client';

// Example of using Prisma types with includes
export type LeadWithAfspraken = Lead & {
  afspraken: Afspraak[];
};

export type AfspraakWithRelations = Afspraak & {
  lead?: Lead | null;
  customer?: Customer | null;
  routeCluster?: RouteCluster | null;
};

export type RouteClusterWithAfspraken = RouteCluster & {
  afspraken: Afspraak[];
};

// Type-safe input types for creating records
export type CreateLeadInput = {
  naam: string;
  email: string;
  telefoon: string;
  adres: string;
  postcode: string;
  stad: string;
  ghlId: string;
  ghlContactId?: string;
  klantType?: 'particulier' | 'zakelijk';
  bedrijfsnaam?: string;
  notities?: string;
};

export type CreateAfspraakInput = {
  leadId?: string;
  customerId?: string;
  datum: Date;
  tijd: string;
  duur?: number;
  locatie: string;
  serviceType: 'installation' | 'maintenance' | 'repair' | 'consultation' | 'installatie' | 'onderhoud' | 'reparatie' | 'consultatie';
  status?: 'gepland' | 'bevestigd' | 'geannuleerd' | 'afgerond' | 'niet_verschenen';
  beschrijving?: string;
  interneNotities?: string;
  googleEventId?: string;
  colorId?: string;
  routeClusterId?: string;
};

export type CreateRouteClusterInput = {
  datum: Date;
  regio: string;
  naam?: string;
  notities?: string;
};

// Export the Prisma client instance type
export { PrismaClient };